"""empty message

Revision ID: 761866979f72
Revises: 2701c6e3bf67
Create Date: 2024-03-06 11:38:45.378142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761866979f72'
down_revision = '2701c6e3bf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
